export const EVENT_TYPES = [
  'RUN_STARTED',
  'PAGE_DETECTED',
  'UNKNOWN_PORTAL_STATE',
  'CHECKPOINT_DETECTED',
  'OTP_REQUIRED',
  'CAPTCHA_REQUIRED',
  'MFA_REQUIRED',
  'ANTI_BOT_DETECTED',
  'CHECKPOINT_STILL_PRESENT',
  'USER_ACTION_REQUIRED',
  'RUN_RESUMED',
  'FIELD_MAP_RESOLVED',
  'FIELD_UNMAPPED',
  'MAPPING_NOT_PRODUCTION_READY',
  'FIELD_ALREADY_SET',
  'FIELD_FILL_STARTED',
  'FIELD_FILLED',
  'FIELD_FILLED_UNVERIFIED',
  'FIELD_VERIFIED',
  'FIELD_MISMATCH',
  'FIELD_UNVERIFIABLE',
  'FIELD_NOT_FOUND',
  'SELECTOR_STALE',
  'DROPDOWN_OPTION_MISSING',
  'VALUE_CONFLICT',
  'FIELD_CONFLICT_KEPT',
  'FIELD_CONFLICT_OVERWRITTEN',
  'VALIDATION_ERROR',
  'NAVIGATION_STARTED',
  'NAVIGATION_COMPLETED',
  'NAVIGATION_STALLED',
  'NAVIGATION_FAILED',
  'DOCUMENT_READY',
  'BLOCKED_MISSING_DOCUMENT',
  'SESSION_EXPIRED',
  'PORTAL_UNAVAILABLE',
  'REVIEW_READY',
  'RUN_PAUSED',
  'RUN_ABORTED',
  'RUN_FAILED',
] as const;

export type EventType = (typeof EVENT_TYPES)[number];

export const EVENT_MESSAGES: Record<EventType, string> = {
  RUN_STARTED: 'The automation run started.',
  PAGE_DETECTED: 'The current portal page was recognised.',
  UNKNOWN_PORTAL_STATE: 'The current portal page could not be recognised. The run paused for your review.',
  CHECKPOINT_DETECTED: 'A security checkpoint appeared on the page. The run paused.',
  OTP_REQUIRED: 'An OTP challenge is on the page. Complete it in the browser, then resume.',
  CAPTCHA_REQUIRED: 'A CAPTCHA challenge is on the page. Complete it in the browser, then resume.',
  MFA_REQUIRED: 'A multi-factor authentication step is on the page. Complete it in the browser, then resume.',
  ANTI_BOT_DETECTED: 'The portal presented an anti-bot check. Complete it in the browser, then resume.',
  CHECKPOINT_STILL_PRESENT: 'The security checkpoint is still on the page. Resume was refused.',
  USER_ACTION_REQUIRED: 'The run needs an action from you in the browser before it can continue.',
  RUN_RESUMED: 'The automation run resumed.',
  FIELD_MAP_RESOLVED: 'A portal control was located for this field.',
  FIELD_UNMAPPED: 'This field has no portal mapping and was left for you to enter.',
  MAPPING_NOT_PRODUCTION_READY:
    'A required portal mapping is not validated against the current mapping revision. The run paused — re-validate the mapping before continuing.',
  FIELD_ALREADY_SET: 'The portal control already held the expected entry, so it was left unchanged.',
  FIELD_FILL_STARTED: 'The run began filling this field.',
  FIELD_FILLED: 'The field was filled and read back as expected.',
  FIELD_FILLED_UNVERIFIED: 'The field was filled and read back as expected, but you have not verified this entry yet.',
  FIELD_VERIFIED: 'The field read back as expected.',
  FIELD_MISMATCH: 'A filled field did not read back as expected. The run paused for your review.',
  FIELD_UNVERIFIABLE: 'The field could not be read back to confirm its contents.',
  FIELD_NOT_FOUND: 'The mapped portal control could not be found on the page.',
  SELECTOR_STALE: 'A portal selector no longer matches the page. The fallback selector was tried.',
  DROPDOWN_OPTION_MISSING: 'The expected option was not present in the dropdown. The run paused.',
  VALUE_CONFLICT: 'The portal already holds a different value for this field. The run paused for your decision.',
  FIELD_CONFLICT_KEPT: 'You chose to keep the value already in the portal for this field.',
  FIELD_CONFLICT_OVERWRITTEN: 'You chose to replace the portal value with your application value for this field.',
  VALIDATION_ERROR: 'The portal reported a validation error on the page. The run paused for your review.',
  NAVIGATION_STARTED: 'The run moved to the next portal page.',
  NAVIGATION_COMPLETED: 'The next portal page finished loading.',
  NAVIGATION_STALLED: 'The portal page did not settle in time. The run paused.',
  NAVIGATION_FAILED: 'The run could not advance to the next portal page.',
  DOCUMENT_READY: 'A required document is prepared and ready in the application.',
  BLOCKED_MISSING_DOCUMENT: 'A required document is missing from the application. The run stopped.',
  SESSION_EXPIRED: 'The portal session expired. Sign in again in the browser, then resume.',
  PORTAL_UNAVAILABLE: 'The portal is not responding. The run stopped.',
  REVIEW_READY: 'The portal reached the final review page. Preparation is complete; submission is yours.',
  RUN_PAUSED: 'The automation run paused at your request.',
  RUN_ABORTED: 'The automation run was cancelled.',
  RUN_FAILED: 'The automation run stopped because of an error.',
};

export function isEventType(x: string): x is EventType {
  return (EVENT_TYPES as readonly string[]).includes(x);
}
