import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { ExtractionError, extractSingleImage } from '../../src/server/documents/pdfImage.js';
import { FakeOcrEngine, ocrResultFromLines } from '../helpers/fakeOcrEngine.js';

/**
 * The PDF fixtures under `test/fixtures/documents/` are synthetic and were
 * generated by the controller during Phase 3 planning — `single-image.pdf` and
 * `multi-page.pdf` from Pillow, `no-image.pdf` a minimal hand-rolled 1-page PDF
 * with only a text stream (zero image XObjects), `encrypted.pdf` hand-rolled
 * with a stdlib RC4 pass over a minimal PDF (user password "secret"). No real
 * document is involved and none contains real personal data.
 */
const FIXTURES = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
  'fixtures',
  'documents',
);
const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

function fixture(name: string): Uint8Array {
  return new Uint8Array(readFileSync(path.join(FIXTURES, name)));
}

/** Walk every PNG chunk and confirm its CRC32 — proves the encoder is sound. */
function assertPngChunkCrcs(png: Uint8Array): number {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  const crc32 = (bytes: Uint8Array): number => {
    let c = 0xffffffff;
    for (let i = 0; i < bytes.length; i += 1) c = table[(c ^ bytes[i]!) & 0xff]! ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
  };
  const view = new DataView(png.buffer, png.byteOffset, png.length);
  let offset = 8;
  let chunks = 0;
  while (offset < png.length) {
    const len = view.getUint32(offset);
    const body = png.subarray(offset + 4, offset + 8 + len);
    const stored = view.getUint32(offset + 8 + len);
    expect(crc32(body) >>> 0).toBe(stored);
    chunks += 1;
    offset += 12 + len;
  }
  expect(offset).toBe(png.length);
  return chunks;
}

describe('extractSingleImage', () => {
  it('unwraps a single-image PDF to a well-formed PNG', async () => {
    const result = await extractSingleImage(fixture('single-image.pdf'));

    expect(result.mime).toBe('image/png');
    expect(result.pageCount).toBe(1);
    expect([...result.bytes.subarray(0, 8)]).toEqual(PNG_SIGNATURE);

    // First chunk after the signature must be IHDR with a sane geometry.
    const view = new DataView(result.bytes.buffer, result.bytes.byteOffset, result.bytes.length);
    expect(view.getUint32(8)).toBe(13); // IHDR length
    expect(String.fromCharCode(...result.bytes.subarray(12, 16))).toBe('IHDR');
    const width = view.getUint32(16);
    const height = view.getUint32(20);
    expect(width).toBeGreaterThan(0);
    expect(height).toBeGreaterThan(0);
    expect(result.bytes[24]).toBe(8); // bit depth
    expect([2, 6]).toContain(result.bytes[25]); // colour type: RGB or RGBA
    // ...and the stream must terminate with an IEND chunk.
    expect(String.fromCharCode(...result.bytes.subarray(result.bytes.length - 8, result.bytes.length - 4))).toBe(
      'IEND',
    );
    // IHDR + >=1 IDAT + IEND, every chunk CRC valid.
    expect(assertPngChunkCrcs(result.bytes)).toBeGreaterThanOrEqual(3);
  });

  it('rejects an encrypted PDF as pdf_encrypted without attempting the password', async () => {
    await expect(extractSingleImage(fixture('encrypted.pdf'))).rejects.toMatchObject({
      name: 'ExtractionError',
      code: 'pdf_encrypted',
    });

    try {
      await extractSingleImage(fixture('encrypted.pdf'));
      expect.unreachable('should have thrown');
    } catch (err) {
      expect(err).toBeInstanceOf(ExtractionError);
      const message = (err as ExtractionError).message;
      expect(message).not.toContain('/');
      expect(message.toLowerCase()).not.toContain('passwd');
      expect(message.toLowerCase()).not.toContain('password');
      expect(message).not.toContain('secret');
      expect(message).not.toContain('fixtures');
    }
  });

  it('rejects a PDF with no image as pdf_unsupported', async () => {
    await expect(extractSingleImage(fixture('no-image.pdf'))).rejects.toMatchObject({
      name: 'ExtractionError',
      code: 'pdf_unsupported',
    });
  });

  it('rejects a multi-page PDF as pdf_unsupported', async () => {
    try {
      await extractSingleImage(fixture('multi-page.pdf'));
      expect.unreachable('should have thrown');
    } catch (err) {
      expect(err).toBeInstanceOf(ExtractionError);
      expect((err as ExtractionError).code).toBe('pdf_unsupported');
    }
  });

  it('rejects garbage bytes as an ExtractionError (no content leak)', async () => {
    try {
      await extractSingleImage(new Uint8Array([1, 2, 3, 4, 5]));
      expect.unreachable('should have thrown');
    } catch (err) {
      expect(err).toBeInstanceOf(ExtractionError);
      expect(['pdf_unsupported', 'unreadable']).toContain((err as ExtractionError).code);
    }
  });
});

describe('FakeOcrEngine', () => {
  it('resolves a fixed OcrResult and records the call', async () => {
    const result = ocrResultFromLines(['LINE ONE', 'LINE TWO'], 91);
    const engine = new FakeOcrEngine(result);
    const bytes = new Uint8Array([9, 9, 9]);

    await expect(engine.recognize(bytes)).resolves.toEqual(result);
    expect(engine.calls).toEqual([bytes]);
  });

  it('invokes a function form with the image bytes', async () => {
    const engine = new FakeOcrEngine((img) => ocrResultFromLines([`len:${img.length}`], 50));
    const out = await engine.recognize(new Uint8Array(4));

    expect(out.text).toBe('len:4');
    expect(engine.calls).toHaveLength(1);
  });

  it('marks disposed on dispose()', async () => {
    const engine = new FakeOcrEngine(ocrResultFromLines(['x']));
    expect(engine.disposed).toBe(false);
    await engine.dispose();
    expect(engine.disposed).toBe(true);
  });
});

describe('ocrResultFromLines', () => {
  it('builds text, lines and meanConfidence', () => {
    expect(ocrResultFromLines(['A', 'B'], 90)).toEqual({
      text: 'A\nB',
      lines: [
        { text: 'A', confidence: 90 },
        { text: 'B', confidence: 90 },
      ],
      meanConfidence: 90,
    });
  });

  it('defaults the confidence to 88', () => {
    expect(ocrResultFromLines(['A']).meanConfidence).toBe(88);
  });
});
